import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import {
  AlertCircle,
  Brain,
  CheckCircle2,
  Eye,
  FileText,
  Loader2,
  PlusCircle,
  RefreshCw,
} from 'lucide-react'

type AiTest = {
  id: string
  title: string
  topic: string
  difficulty: string
  numberOfQuestions: number
  durationMinutes: number
  passingPercentage: number
  status: string
  generatedQuestions: number
  failedReason: string
  createdAt: string
  updatedAt: string
  completedAt: string
}

type AiTestsResponse = {
  tests: AiTest[]
}

const gcpBackendBaseUrl = 'https://testbridge-backend-ukm3galdsq-el.a.run.app'
const adminApiKey = 'testbridge-admin-2026'

function formatDate(value: string): string {
  if (!value) return 'N/A'

  const date = new Date(value)

  if (Number.isNaN(date.getTime())) {
    return value
  }

  return date.toLocaleString()
}

function getStatusClassName(status: string): string {
  if (status === 'DRAFT') return 'status-badge approved'
  if (status === 'FAILED') return 'status-badge rejected'
  if (status === 'GENERATING') return 'status-badge pending'

  return 'status-badge'
}

async function getApiErrorMessage(response: Response): Promise<string> {
  try {
    const responseText = await response.text()

    if (!responseText) {
      return `Request failed with status ${response.status}.`
    }

    try {
      const parsed = JSON.parse(responseText) as { message?: string }
      return parsed.message || responseText
    } catch {
      return responseText
    }
  } catch {
    return `Request failed with status ${response.status}.`
  }
}

function AdminAiTestsPage() {
  const navigate = useNavigate()

  const [tests, setTests] = useState<AiTest[]>([])
  const [isLoading, setIsLoading] = useState(true)
  const [errorMessage, setErrorMessage] = useState('')

  async function loadAiTests() {
    setIsLoading(true)
    setErrorMessage('')

    try {
      const response = await fetch(`${gcpBackendBaseUrl}/api/ai-tests`, {
        method: 'GET',
        headers: {
          'x-admin-key': adminApiKey,
        },
      })

      if (!response.ok) {
        const detailedMessage = await getApiErrorMessage(response)
        setErrorMessage(detailedMessage)
        return
      }

      const data = (await response.json()) as AiTestsResponse
      setTests(Array.isArray(data.tests) ? data.tests : [])
    } catch (error) {
      const detailedMessage =
        error instanceof Error
          ? error.message
          : 'Unable to load AI generated tests.'

      setErrorMessage(detailedMessage)
    } finally {
      setIsLoading(false)
    }
  }

  useEffect(() => {
    void loadAiTests()
  }, [])

  return (
    <main className="page-shell">
      <section className="dashboard-header">
        <div>
          <p className="eyebrow">Admin AI Review</p>
          <h1>AI Generated Tests</h1>
          <p>
            View tests generated by AI from Firestore. Admin can review the
            questions before publishing them to users.
          </p>
        </div>

        <div className="dashboard-actions">
          <button
            type="button"
            className="secondary-button"
            onClick={() => void loadAiTests()}
            disabled={isLoading}
          >
            {isLoading ? (
              <Loader2 size={18} className="spin-icon" />
            ) : (
              <RefreshCw size={18} />
            )}
            Refresh
          </button>

          <button
            type="button"
            className="primary-button"
            onClick={() => navigate('/admin/ai-test-generator')}
          >
            <PlusCircle size={18} />
            Create AI Test
          </button>
        </div>
      </section>

      {errorMessage ? (
        <div className="alert-message alert-error">
          <AlertCircle size={18} />
          {errorMessage}
        </div>
      ) : null}

      <section className="content-card">
        <div className="section-title-row">
          <div>
            <h2>Firestore Draft Tests</h2>
            <p>
              These tests are currently stored in GCP Firestore collection
              ai_tests.
            </p>
          </div>
        </div>

        {isLoading ? (
          <div className="placeholder-card">
            <Loader2 size={24} className="spin-icon" />
            <h2>Loading AI tests...</h2>
            <p>Please wait while we load generated tests from Firestore.</p>
          </div>
        ) : tests.length === 0 ? (
          <div className="placeholder-card">
            <Brain size={28} />
            <h2>No AI tests found</h2>
            <p>Create your first AI test from the AI Test Generator page.</p>
          </div>
        ) : (
          <div className="responsive-table-wrapper">
            <table className="data-table">
              <thead>
                <tr>
                  <th>Test</th>
                  <th>Topic</th>
                  <th>Difficulty</th>
                  <th>Questions</th>
                  <th>Duration</th>
                  <th>Passing</th>
                  <th>Status</th>
                  <th>Created</th>
                  <th>Review</th>
                </tr>
              </thead>

              <tbody>
                {tests.map((test) => (
                  <tr key={test.id}>
                    <td>
                      <div>
                        <strong>{test.title}</strong>
                        <p className="muted-text">{test.id}</p>
                      </div>
                    </td>

                    <td>{test.topic}</td>
                    <td>{test.difficulty}</td>

                    <td>
                      {test.generatedQuestions}/{test.numberOfQuestions}
                    </td>

                    <td>{test.durationMinutes} min</td>
                    <td>{test.passingPercentage}%</td>

                    <td>
                      <span className={getStatusClassName(test.status)}>
                        {test.status === 'DRAFT' ? (
                          <CheckCircle2 size={14} />
                        ) : test.status === 'GENERATING' ? (
                          <Loader2 size={14} className="spin-icon" />
                        ) : (
                          <FileText size={14} />
                        )}
                        {test.status || 'UNKNOWN'}
                      </span>

                      {test.failedReason ? (
                        <p className="muted-text">{test.failedReason}</p>
                      ) : null}
                    </td>

                    <td>{formatDate(test.createdAt)}</td>

                    <td>
                      <button
                        type="button"
                        className="secondary-button small-button"
                        onClick={() =>
                          navigate(`/admin/ai-tests/${test.id}/review`)
                        }
                        disabled={test.status !== 'DRAFT'}
                      >
                        <Eye size={16} />
                        Review
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </section>
    </main>
  )
}

export default AdminAiTestsPage